version: 2
jobs:
  build-stable:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get -y install gcc cmake make build-essential python3 python3-pip
    - run:
        command: pip install conan
    - run:
        command: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
    - run:
        command: mkdir build && cd build && conan install .. -o antlr4=4.11.1
    - run:
        command: cd build && conan build ..
    - run:
        command: cd build && a4test
workflows:
  version: 2