version: 2.1
jobs:

  build-stable:
    working_directory: ~
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: uname -a && cat /proc/version && cat /etc/issue
      - run: sudo apt-get update && sudo apt-get -y install gcc cmake make build-essential python3 python3-pip default-jre
      - run: pip install conan==1.59
      - run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: cd build && conan source ..
      - run: cd build && conan install ..
      - run: cd Src && source regenerate_parser.sh
      - run: cd build && conan build ..
      - run: cd build && a4test

workflows:
  version: 2
  commit:
    jobs:
      - build-stable:
          filters:
            branches:
              only:
                 - main
                 - /issue_.*/

  nightly:
    triggers:
      - schedule:
          # https://crontab.guru/#0_1_*_*_3
          cron: "0 1 * * 1,6"
          filters:
            branches:
              only:
                - main
                - /issue_.*/
    jobs:
      - build-stable
