version: 2.1
jobs:

  build-stable:
    working_directory: ~
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run: uname -a && cat /proc/version && cat /etc/issue
      - run: sudo apt-get update && sudo apt-get -y install gcc cmake make build-essential python3 python3-pip default-jre
      - run: sudo ln -s /usr/bin/pip3 /usr/bin/pip
      - run: pip install --upgrade pip
      - run: pip install conan
      - run: conan profile detect
      - run: conan source .
      - run: conan install . -s build_type=Debug --build missing
      - run: conan build . -s build_type=Debug --build missing
      - run: ./build/Debug/a4test

workflows:
  version: 2
  commit:
    jobs:
      - build-stable:
          filters:
            branches:
              only:
                 - main
                 - /issue_.*/

  nightly:
    triggers:
      - schedule:
          # https://crontab.guru/#0_1_*_*_3
          cron: "0 1 * * 3"
          filters:
            branches:
              only:
                - main
                - /issue_.*/
    jobs:
      - build-stable
